#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Mon Jan 13 18:29:54 UTC 2025
a=false
another_furniture=true
beautify=true
campchair=true
chipped=true
create=true
farmersdelight=true
friendsandfoes=true
handcrafted=true
mcwbridges=true
mcwdoors=true
mcwfences=true
mcwfurnitures=true
mcwlights=true
mcwpaths=true
mcwroofs=true
mcwtrpdoors=true
mcwwindows=true
mighty_mail=true
refurbished_furniture=true
twigs=true
